export const example = {
    playerCharacter: {
        abilityScores: [
            { amount: 10, ability: "Strength" },
            { amount: 10, ability: "Dexterity" },
            { amount: 10, ability: "Constitution" },
            { amount: 10, ability: "Intelligence" },
            { amount: 10, ability: "Wisdom" },
            { amount: 10, ability: "Charisma" },
        ],
        languages: [" Common", " Dwarf", " Goblin"],
        skills: [
            {
                name: "Acrobatics",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Arcana",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Atheltics",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Crafting",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Deception",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Diplomacy",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Intimidation",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Lore",
                loreDescriptor: "Golarion",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Medicine",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Nature",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Occultism",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Performance",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Religion",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Society",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Stealth",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Survival",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: false,
            },
            {
                name: "Thievery",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 2,
            },
        ],
        ancestryFeatsAndAbilities: [
            { title: "Special 1st", description: "Dwarf Stuff" },
            { title: "Heritage 1st", description: "other Dwarf Stuff" },
            { title: "Feat 1st", description: "other Dwarf Stuff" },
            { title: "Feat 5th", description: "other Dwarf Stuff" },
            { title: "Feat 9th", description: "other Dwarf Stuff" },
            { title: "Feat 13th", description: "other Dwarf Stuff" },
            { title: "Feat 17th", description: "other Dwarf Stuff" },
        ],
        skillFeats: [
            { title: "Background", description: "Dwarf Stuff" },
            { title: "2nd", description: "other Dwarf Stuff" },
            { title: "4th", description: "other Dwarf Stuff" },
            { title: "6th", description: "other Dwarf Stuff" },
            { title: "8th", description: "other Dwarf Stuff" },
            { title: "10th", description: "other Dwarf Stuff" },
            { title: "12th", description: "other Dwarf Stuff" },
            { title: "14th", description: "other Dwarf Stuff" },
            { title: "16th", description: "other Dwarf Stuff" },
            { title: "18th", description: "other Dwarf Stuff" },
            { title: "20th", description: "other Dwarf Stuff" },
        ],
        generalFeats: [
            { title: "3rd", description: "Dwarf Stuff" },
            { title: "7th", description: "other Dwarf Stuff" },
            { title: "11th", description: "other Dwarf Stuff" },
            { title: "15th", description: "other Dwarf Stuff" },
            { title: "19th", description: "other Dwarf Stuff" },
        ],
        classFeatsAndAbilities: [
            { title: "Feature 1st", description: "Dwarf Stuff" },
            { title: "Feature 1st", description: "Dwarf Stuff" },
            { title: "Feat 1st", description: "other Dwarf Stuff" },
            { title: "Feat 2nd", description: "other Dwarf Stuff" },
            { title: "Feature 3rd", description: "other Dwarf Stuff" },
            { title: "Feat 4th", description: "other Dwarf Stuff" },
            { title: "Feature 5th", description: "other Dwarf Stuff" },
            { title: "Feat 6th", description: "other Dwarf Stuff" },
            { title: "Feature 7th", description: "other Dwarf Stuff" },
            { title: "Feat 8th", description: "other Dwarf Stuff" },
            { title: "Feature 9th", description: "other Dwarf Stuff" },
            { title: "Feat 10th", description: "other Dwarf Stuff" },
            { title: "Feature 11th", description: "other Dwarf Stuff" },
            { title: "Feat 12th", description: "other Dwarf Stuff" },
            { title: "Feature 13th", description: "other Dwarf Stuff" },
            { title: "Feat 14th", description: "other Dwarf Stuff" },
            { title: "Feature 15th", description: "other Dwarf Stuff" },
            { title: "Feat 16th", description: "other Dwarf Stuff" },
            { title: "Feature 17th", description: "other Dwarf Stuff" },
            { title: "Feat 18th", description: "other Dwarf Stuff" },
            { title: "Feature 19th", description: "other Dwarf Stuff" },
            { title: "Feat 20th", description: "other Dwarf Stuff" },
        ],
        bonusFeats: [
            { title: "Bonus1", description: "Dwarf Stuff" },
            { title: "Bonus2", description: "other Dwarf Stuff" },
        ],
        inventory: {
            items: [
                {
                    itemName: "Doubling Rings",
                    bulk: 0,
                    invested: true,
                    worn: true,
                    readied: false,
                },
                {
                    itemName: "Bracers of Missile Deflection",
                    bulk: 0.1,
                    invested: true,
                    worn: true,
                    readied: false,
                },
                {
                    itemName: "Alchemist's Fire",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: true,
                },
                {
                    itemName: "Thieves Tools",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: true,
                },
                {
                    itemName: "Feather Token (Ladder)",
                    bulk: 0,
                    invested: false,
                    worn: false,
                    readied: false,
                },
                {
                    itemName: "Signal Whistle",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: false,
                },
            ],
        },
    },
};
