export const example = {
    playerCharacter: {
        level: 1,
        abilityScores: [
            { amount: 10, ability: "Strength" },
            { amount: 10, ability: "Dexterity" },
            { amount: 10, ability: "Constitution" },
            { amount: 10, ability: "Intelligence" },
            { amount: 10, ability: "Wisdom" },
            { amount: 10, ability: "Charisma" },
        ],
        languages: [" Common", " Dwarf", " Goblin"],
        skills: [
            {
                name: "Acrobatics",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Arcana",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Atheltics",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Crafting",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Deception",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Diplomacy",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Intimidation",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Lore",
                loreDescriptor: "Golarion",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Medicine",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Nature",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Occultism",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Performance",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Religion",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Society",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Stealth",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 0,
            },
            {
                name: "Survival",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: false,
            },
            {
                name: "Thievery",
                abilityModifier: 3,
                proficiency: "Trained",
                itemBonus: 1,
                hasArmorPenalty: true,
                armorPenalty: 2,
            },
        ],
        ancestryFeatsAndAbilities: [
            { title: "Special 1st", description: "Dwarf Stuff" },
            { title: "Heritage 1st", description: "other Dwarf Stuff" },
            { title: "Feat 1st", description: "other Dwarf Stuff" },
            { title: "Feat 5th", description: "other Dwarf Stuff" },
            { title: "Feat 9th", description: "other Dwarf Stuff" },
            { title: "Feat 13th", description: "other Dwarf Stuff" },
            { title: "Feat 17th", description: "other Dwarf Stuff" },
        ],
        skillFeats: [
            { title: "Background", description: "Dwarf Stuff" },
            { title: "2nd", description: "other Dwarf Stuff" },
            { title: "4th", description: "other Dwarf Stuff" },
            { title: "6th", description: "other Dwarf Stuff" },
            { title: "8th", description: "other Dwarf Stuff" },
            { title: "10th", description: "other Dwarf Stuff" },
            { title: "12th", description: "other Dwarf Stuff" },
            { title: "14th", description: "other Dwarf Stuff" },
            { title: "16th", description: "other Dwarf Stuff" },
            { title: "18th", description: "other Dwarf Stuff" },
            { title: "20th", description: "other Dwarf Stuff" },
        ],
        generalFeats: [
            { title: "3rd", description: "Dwarf Stuff" },
            { title: "7th", description: "other Dwarf Stuff" },
            { title: "11th", description: "other Dwarf Stuff" },
            { title: "15th", description: "other Dwarf Stuff" },
            { title: "19th", description: "other Dwarf Stuff" },
        ],
        classFeatsAndAbilities: [
            { title: "Feature 1st", description: "Dwarf Stuff" },
            { title: "-Feature 1st", description: "Dwarf Stuff" },
            { title: "Feat 1st", description: "other Dwarf Stuff" },
            { title: "Feat 2nd", description: "other Dwarf Stuff" },
            { title: "Feature 3rd", description: "other Dwarf Stuff" },
            { title: "Feat 4th", description: "other Dwarf Stuff" },
            { title: "Feature 5th", description: "other Dwarf Stuff" },
            { title: "Feat 6th", description: "other Dwarf Stuff" },
            { title: "Feature 7th", description: "other Dwarf Stuff" },
            { title: "Feat 8th", description: "other Dwarf Stuff" },
            { title: "Feature 9th", description: "other Dwarf Stuff" },
            { title: "Feat 10th", description: "other Dwarf Stuff" },
            { title: "Feature 11th", description: "other Dwarf Stuff" },
            { title: "Feat 12th", description: "other Dwarf Stuff" },
            { title: "Feature 13th", description: "other Dwarf Stuff" },
            { title: "Feat 14th", description: "other Dwarf Stuff" },
            { title: "Feature 15th", description: "other Dwarf Stuff" },
            { title: "Feat 16th", description: "other Dwarf Stuff" },
            { title: "Feature 17th", description: "other Dwarf Stuff" },
            { title: "Feat 18th", description: "other Dwarf Stuff" },
            { title: "Feature 19th", description: "other Dwarf Stuff" },
            { title: "Feat 20th", description: "other Dwarf Stuff" },
        ],
        bonusFeats: [
            { title: "Bonus1", description: "Dwarf Stuff" },
            { title: "Bonus2", description: "other Dwarf Stuff" },
        ],
        inventory: {
            items: [
                {
                    itemName: "Doubling Rings",
                    bulk: 0,
                    invested: true,
                    worn: true,
                    readied: false,
                },
                {
                    itemName: "Bracers of Missile Deflection",
                    bulk: 0.1,
                    invested: true,
                    worn: true,
                    readied: false,
                },
                {
                    itemName: "Alchemist's Fire",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: true,
                },
                {
                    itemName: "Thieves Tools",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: true,
                },
                {
                    itemName: "Feather Token (Ladder)",
                    bulk: 0,
                    invested: false,
                    worn: false,
                    readied: false,
                },
                {
                    itemName: "Signal Whistle",
                    bulk: 0.1,
                    invested: false,
                    worn: false,
                    readied: false,
                },
            ],
        },
        biographicalData: {
            ethnicity: "Varisian",
            nationality: "Absalomnian",
            birthplace: "Absalom",
            age: 89,
            gender: "M",
            height: 70,
            weight: 210,
            appearance: "middle height fair skin moderate looks",
        },
        personalityData: {
            attitude: "sassy",
            beliefs: "all people are good",
            likes: "peanut butter",
            dislikes: "sassy people",
            catchphrases: "to infinity and beyond!",
        },
        campaignNotesData: {
            notes:
                "this is my campaign notes. They are thorough and they help my GM keep track of that various things that we do so he doesn't have to do all the work.",
            allies: "my trusty sword, my trusty dagger, my cat",
            enemies: "World Hungry",
            organizations: "PETA, NRA, PFS, LP",
        },
        actions: [
            {
                name: "Shove",
                numberOfActions: 1,
                traits: ["Attack", "Atheletics"],
                bookAbbreviation: "CRB",
                pageNumber: 242,
                description:
                    "You shove your foe away and stuff. You can go too, if you want.",
            },
            {
                name: "Power Attack",
                numberOfActions: 2,
                traits: ["Attack", "Flourish"],
                bookAbbreviation: "CRB",
                pageNumber: 278,
                description: "Moar damage dice!",
            },
            {
                name: "Speak out loud",
                numberOfActions: 0,
                traits: ["Free Action", "Verbal"],
                bookAbbreviation: "CRB",
                pageNumber: 1,
                description: "You speak. Like a dog.",
            },
            {
                name: "Attack of Opportunity",
                numberOfActions: 0.5,
                traits: [],
                bookAbbreviation: "CRB",
                pageNumber: 142,
                description:
                    "You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn’t count toward your multiple attack penalty, and your multiple attack penalty doesn’t apply to this Strike.",
                trigger:
                    "A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it’s using.",
            },
        ],
        spellcastingAbilityModifier: 2,
        spellAttackProficiency: "Trained",
        bonuses: [
            { type: "item", appliesTo: "spellAttack", amount: 1 },
            { type: "item", appliesTo: "spellAttack", amount: 4 },
            { type: "item", appliesTo: "spellAttack", amount: 2 },
            { type: "item", appliesTo: "spellAttack", amount: 1 },
        ],
        penalties: [],
        magicTraditions: {
            prepared: true,
            spontaneous: false,
            arcane: true,
            primal: false,
            divine: true,
            occult: false,
        },
        spellSlots: [
            {
                spellLevel: "Focus",
                maximum: 1,
                current: 0,
            },
            {
                spellLevel: "1st",
                maximum: 3,
                current: 3,
            },
            {
                spellLevel: "2nd",
                maximum: 3,
                current: 3,
            },
            {
                spellLevel: "3rd",
                maximum: 2,
                current: 1,
            },
            {
                spellLevel: "4th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "5th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "6th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "7th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "8th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "9th",
                maximum: 0,
                current: 0,
            },
            {
                spellLevel: "10th",
                maximum: 0,
                current: 0,
            },
        ],
        spells: [
            {
                spellType: "Focus",
                data: [
                    {
                        actionAbbr: "2",
                        cast: null,
                        components: ["Somatic", "Verbal"],
                        description:
                            "You become a mantis. You gain the effects of *insect form*, heightened to *mantis form*'s level, and you can only transform into a mantis.",
                        duration: "1 minute",
                        has_been_manually_proofread: false,
                        level: 4,
                        name: "Mantis Form",
                        req: null,
                        source: {
                            abbr: "LOWG",
                            page_start: 71,
                            page_stop: 71,
                        },
                        targets: null,
                        traditions: null,
                        traits: ["Uncommon", "Polymorph", "Transmutation"],
                        trigger: null,
                        type: "Focus",
                    },
                ],
            },
            {
                spellType: "1st Level",
                data: [
                    {
                        actionAbbr: ["1", "2", "3"],
                        cast: "|1| to |3|",
                        components: null,
                        description:
                            "You channel positive energy to heal the living or damage the undead. If the target is a willing living creature, you restore 1d8 Hit Points. If the target is undead, you deal that amount of positive damage to it, and it gets a basic Fortitude save. The number of actions you spend when Casting this Spell determines its targets, range, area, and other parameters.  \n\n  \n\n |1| (somatic) The spell has a range of touch.  \n\n |2| (verbal, somatic) The spell has a range of 30 feet. If you're healing a living creature, increase the Hit Points restored by 8.  \n\n |3| (material, somatic, verbal) You disperse positive energy in a 30-foot emanation. This targets all living and undead creatures in the burst.  \n\n**Heightened (+1)**  The amount of healing or damage increases by 1d8, and the extra healing for the 2-action version increases by 8.",
                        duration: null,
                        has_been_manually_proofread: false,
                        heightened: [
                            {
                                damagetype_name: "Positive",
                                description:
                                    "**Heightened (+1)** The amount of healing or damage increases by 1d8, and the extra healing for the 2-action version increases by 8.",
                                formula: "1d8",
                                type: 1,
                            },
                        ],
                        level: 1,
                        name: "Heal",
                        range: "varies",
                        requirements: null,
                        rolls: [
                            {
                                action_abbr: "1",
                                components: ["Somatic"],
                                damagetype_name: "Positive",
                                dice: "1d8",
                                range: "Touch",
                            },
                            {
                                action_abbr: "2",
                                components: ["Somatic", "Verbal"],
                                damagetype_name: "Positive",
                                description:
                                    "If you're healing a living creature, increase the Hit Points restored by 8.",
                                dice: "1d8",
                                range: "30 feet",
                            },
                            {
                                action_abbr: "3",
                                components: ["Material", "Somatic", "Verbal"],
                                damagetype_name: "Positive",
                                description:
                                    "You disperse positive energy in a 30-foot emanation. This targets all living and undead creatures in the burst.",
                                dice: "1d8",
                                range: "30-foot emanation",
                            },
                        ],
                        source: {
                            abbr: "CRB",
                            page_start: 342,
                            page_stop: 342,
                        },
                        targets:
                            "1 willing living creature or 1 undead creature",
                        traditions: ["Divine", "Primal"],
                        traits: ["Healing", "Necromancy", "Positive"],
                        trigger: null,
                        type: "Spell",
                    },
                ],
            },
            {
                spellType: "2nd Level",
                data: [],
            },
            {
                spellType: "3rd Level",
                data: [],
            },
            {
                spellType: "4th Level",
                data: [],
            },
            {
                spellType: "5th Level",
                data: [],
            },
            {
                spellType: "6th Level",
                data: [],
            },
            {
                spellType: "7th Level",
                data: [],
            },
            {
                spellType: "8th Level",
                data: [],
            },
            {
                spellType: "9th Level",
                data: [],
            },
            {
                spellType: "10th Level",
                data: [],
            },
        ],
    },
};
